---
# Dependencies install
- hosts: appServer
  become: yes
  become_user: root
  become_method: sudo
  tasks:

    - name: Add repository
      yum_repository:
        name: ium
        description: Repositorio Python
        baseurl: https://centos7.iuscommunity.org/ius-release.rpm

    - name: Install python3
      yum:
        name:
          - python-setuptools
          - python36u
          - python36u-libs
          - python36u-pip
          - python36u-devel
        state: present

